### ISSUE TITLE
Twilio voice call fails without any error  

### ISSUE THREAD

**Issue by dhamo-pk** [fabasoad/twilio-voice-call-action#90] opened 2022-11-29 22:37 UTC
#### Describe the bug
After the successful set up of the twilio account including the verified phone number, voice call fails after 1 day of usage

#### Steps to Reproduce
1. Set up in github actions pipeline
2. Use it for more than a day
3. See if you are getting the call or not

#### Expected behavior
Call should be made. If it fails, throw the error why it is failed. 

#### Actual behavior
No error at all and just no voice call made. 

#### Screenshots
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/44419390/204661690-6d1b60a4-4cd4-44c2-bffa-2dcd86eb4b47.png">

#### Technical information (please complete the following information):

 ```
-  name: Twilio voice call
        uses: fabasoad/twilio-voice-call-action@main
        if: failure()
        with:
          text: 'GitHub actions build number ${{ github.run_number }} passed successfully.'
          from: '+45verifiednumber'
          to: '+45anynumber'
          twilio_account_sid: 'my sid from twilio' #'${{ secrets.TWILIO_ACCOUNT_SID }}
          twilio_auth_token: 'my token from twilio'#'${{ secrets.TWILIO_AUTH_TOKEN }}

```
#### Additional context
It is how it is being displayed while expanding the previous image for this section. Removed the credentials intentionally. 
```

Run fabasoad/twilio-voice-call-action@main
  with:
    text: GitHub actions build number 395 passed successfully.
    from: +45XYZ
    to: +45YUX
    twilio_account_sid: BLA BLA BLA
    twilio_auth_token: BLA BLA BLA
    voice: alice
```

**Comment by fabasoad** [comment] 2022-11-30 13:15
@dhamo-pk thanks for opening this issue. This error sounds strange TBH. I will try to reproduce it. A few minutes ago made a call. All works fine so far. Will see tomorrow and the day after tomorrow. I will let you know.

**Comment by fabasoad** [comment] 2022-12-02 06:14
@dhamo-pk Just checked again and it works for me. So, likely the issue you have is not on this GHA side. Please double check on your side - phone connection problem, Twilio account credentials or phone numbers, etc.

Will try again tomorrow and if it will work for me then I will close this ticket.

**Closed** 2022-12-02 15:48 UTC
Labels: bug
